services:
  gatsby:
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    command: gatsby develop -H 0.0.0.0
