services:
  gatsby:
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./src/public:/app/src/public  # 追加: ビルド成果物を共有
    tty: true
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
